version: "3"

services:

  db:
    ports:
      - ${DB_PORT}:3306

  mage2:
    build:
      context: .
      args:
        - PHP_SERVER_VER=${PHP_SERVER_VER}
        - REDIS_VER=${REDIS_VER}
        - XDEBUG_VER=${XDEBUG_VER}

  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
      args:
        - COMPOSER_VER=${COMPOSER_VER}
        - PHP_CLI_VER=${PHP_CLI_VER}
        - REDIS_VER=${REDIS_VER}
    environment:
      MAGE2_PARAMS: ${MAGE2_PARAMS}
      MAGE2_USE_SAMPLE_DATA: ${MAGE2_USE_SAMPLE_DATA}
      MAGE2_VARNISH_FPC: ${MAGE2_VARNISH_FPC}
