version: "3"

services:

  traefik:
    image: traefik:2.1

  varnish:
    image: varnish:6.0
    depends_on:
      - nginx

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - mage2

  db:
    image: mariadb:10.2

  rediscache:
    image: redis:5-alpine
    depends_on:
      - db
      - mage2

  redissession:
    image: redis:5-alpine
    depends_on:
      - db
      - mage2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    depends_on:
      - db

  mage2:
    image: ${MAGE2FPM_IMAGE}
    depends_on:
      - db

  cli:
    image: ${MAGE2CLI_IMAGE}
    depends_on:
      - db
      - rediscache
      - redissession
      - elasticsearch

  cron:
    image: ${MAGE2CRON_IMAGE}
    depends_on:
      - db
      - mage2
      - elasticsearch
      - rediscache
      - redissession
