version: "3"

services:

  haproxy:
    ports:
      - ${HAPROXY_PORT}:80
    volumes:
      - ./docker/haproxy/config/:/usr/local/etc/haproxy:ro
    restart: on-failure

  varnish:
    build:
      context: ./docker/varnish
    env_file:
      ./docker/varnish/mage2varnish.env
    volumes:
      - ./docker/varnish/config/default.vcl:/etc/varnish/default.vcl
    restart: on-failure

  nginx:
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:${MAGE2_ROOT}:ro
      - ./docker/nginx/config/mage2playground.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

  db:
    ports:
      - ${DB_PORT}:3306
    env_file:
      ./docker/db/mage2db.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  rediscache:
    restart: on-failure

  redissession:
    restart: on-failure

  elasticsearch:
    image: mage2elastic:${ES_VER}
    build:
      context: ./docker/elasticsearch
      args:
        - ES_VER=${ES_VER}
    ports:
      - ${ES_PORT}:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    restart: on-failure

  mage2:
    build:
      context: .
      args:
        - MAGE2_UID=${MAGE2_UID}
        - MAGE2_GID=${MAGE2_GID}
        - PHP_SERVER_VER=${PHP_SERVER_VER}
        - PHP_REDIS_VER=${PHP_REDIS_VER}
        - PHP_XDEBUG_VER=${PHP_XDEBUG_VER}
    environment:
      MAGE2_UID: ${MAGE2_UID}
      MAGE2_GID: ${MAGE2_GID}
    volumes:
      - ./:${MAGE2_ROOT}

  cli:
    build:
      context: ./docker/cli
      args:
        - MAGE2_UID=${MAGE2_UID}
        - MAGE2_GID=${MAGE2_GID}
        - COMPOSER_VER=${COMPOSER_VER}
        - PHP_CLI_VER=${PHP_CLI_VER}
        - PHP_REDIS_VER=${PHP_REDIS_VER}
    env_file:
      ./docker/cli/mage2cli.env
    environment:
      MAGE2_UID: ${MAGE2_UID}
      MAGE2_GID: ${MAGE2_GID}
    volumes:
      - ./:${MAGE2_ROOT}

  cron:
    build:
      context: ./docker/cron
      args:
        - MAGE2CLI_IMAGE=${MAGE2CLI_IMAGE}
    environment:
      MAGE2_UID: ${MAGE2_UID}
      MAGE2_GID: ${MAGE2_GID}
    volumes:
      - ./:${MAGE2_ROOT}
    restart: on-failure

volumes:
  esdata:
  mariadb:
    external: true
