version: "3"

services:

  db:
    ports:
      - ${DB_PORT}:3306

  elasticsearch:
    ports:
      - ${ES_PORT}:9200

  cli:
    environment:
      MAGE2_INSTALL_PARAMS: ${MAGE2_INSTALL_PARAMS}
      MAGE2_USE_SAMPLE_DATA: ${MAGE2_USE_SAMPLE_DATA}
      MAGE2_VARNISH_FPC: ${MAGE2_VARNISH_FPC}
