version: "3"

services:

  varnish:
    build:
      context: ./docker/varnish
    ports:
      - ${VARNISH_PORT}:80
    restart: on-failure

  nginx:
    ports:
      - ${NGINX_PORT}:80
    restart: on-failure

  db:
    ports:
      - ${DB_PORT}:3306
    restart: on-failure

  rediscache:
    restart: on-failure

  redissession:
    restart: on-failure

  elasticsearch:
    image: mage2elastic:${ES_VER}
    build:
      context: ./docker/elasticsearch
      args:
        - ES_VER=${ES_VER}
    ports:
      - ${ES_PORT}:9200
    restart: on-failure

  mage2:
    build:
      context: .
      args:
        - PHP_SERVER_VER=${PHP_SERVER_VER}
        - PHP_REDIS_VER=${PHP_REDIS_VER}
        - PHP_XDEBUG_VER=${PHP_XDEBUG_VER}
    volumes:
      - ./app/etc/env.php:${MAGE2_ROOT}/app/etc/env.php
      - ./app/code:${MAGE2_ROOT}/app/code
      - ./app/design:${MAGE2_ROOT}/app/design
      - ./dev:${MAGE2_ROOT}/dev
      - ./lib:${MAGE2_ROOT}/lib
      - ./vendor:${MAGE2_ROOT}/vendor
      - ./composer.json:${MAGE2_ROOT}/composer.json
      - ./composer.lock:${MAGE2_ROOT}/composer.lock

  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
      args:
        - COMPOSER_VER=${COMPOSER_VER}
        - PHP_CLI_VER=${PHP_CLI_VER}
        - PHP_REDIS_VER=${PHP_REDIS_VER}
    environment:
      MAGE2_INSTALL_PARAMS: ${MAGE2_INSTALL_PARAMS}
      MAGE2_USE_SAMPLE_DATA: ${MAGE2_USE_SAMPLE_DATA}
      MAGE2_VARNISH_FPC: ${MAGE2_VARNISH_FPC}

  cron:
    build:
      context: ./docker/cron
      args:
        - MAGE2CLI_IMAGE=${MAGE2CLI_IMAGE}
    restart: on-failure
