version: "3"

services:

  vue-s8t:
    image: ${VUESTOREFRONT_IMAGE}
    build:
      context: ${MAGE2VUE_PATH}
      dockerfile: ./docker/vue-storefront/Dockerfile
    env_file:
      - ${MAGE2VUE_PATH}/docker/vue-storefront/default.env
      - ./docker/vuestorefront/mage2vue.env
    volumes:
      - ${MAGE2VUE_PATH}/.babelrc:/var/www/.babelrc
      - ${MAGE2VUE_PATH}/config:/var/www/config
      - ${MAGE2VUE_PATH}/core:/var/www/core
      - ${MAGE2VUE_PATH}/ecosystem.json:/var/www/ecosystem.json
      - ${MAGE2VUE_PATH}/.eslintignore:/var/www/.eslintignore
      - ${MAGE2VUE_PATH}/.eslintrc.js:/var/www/.eslintrc.js
      - ${MAGE2VUE_PATH}/lerna.json:/var/www/lerna.json
      - ${MAGE2VUE_PATH}/tsconfig.json:/var/www/tsconfig.json
      - ${MAGE2VUE_PATH}/tsconfig-build.json:/var/www/tsconfig-build.json
      - ${MAGE2VUE_PATH}/shims.d.ts:/var/www/shims.d.ts
      - ${MAGE2VUE_PATH}/package.json:/var/www/package.json
      - ${MAGE2VUE_PATH}/src:/var/www/src
      - ${MAGE2VUE_PATH}/var:/var/www/var
    tmpfs:
      - /var/www/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-s8t.entrypoints=web"
      - "traefik.http.routers.vue-s8t.rule=Host(`storefront.docker`, `www.storefront.docker`)"
      - "traefik.http.services.vue-s8t.loadbalancer.server.port=3000"
    ports:
      - 3000

  vue-s8t-api:
    image: ${VUESTOREFRONT_API_IMAGE}
    build:
      context: ${MAGE2VUE_API_PATH}
      dockerfile: ./docker/vue-storefront-api/Dockerfile
    depends_on:
      - elasticsearch
      - rediscache
    env_file:
      - ${MAGE2VUE_API_PATH}/docker/vue-storefront-api/default.env
      - ./docker/vuestorefront/mage2vue.env
    volumes:
      - ${MAGE2VUE_API_PATH}/config:/var/www/config
      - ${MAGE2VUE_API_PATH}/ecosystem.json:/var/www/ecosystem.json
      - ${MAGE2VUE_API_PATH}/migrations:/var/www/migrations
      - ${MAGE2VUE_API_PATH}/package.json:/var/www/package.json
      - ${MAGE2VUE_API_PATH}/scripts:/var/www/scripts
      - ${MAGE2VUE_API_PATH}/src:/var/www/src
      - ${MAGE2VUE_API_PATH}/var:/var/www/var
    tmpfs:
      - /var/www/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-s8t-api.entrypoints=web"
      - "traefik.http.routers.vue-s8t-api.rule=Host(`api.storefront.docker`, `www.api.storefront.docker`)"
      - "traefik.http.services.vue-s8t-api.loadbalancer.server.port=8080"
    ports:
      - 8080
