version: "3"

services:

  varnish:
    build:
      context: ./docker/varnish

  mage2:
    build:
      context: .
      args:
        - COMPOSER_VER=${COMPOSER_VER}
        - PHP_SERVER_VER=${PHP_SERVER_VER}
        - REDIS_VER=${REDIS_VER}
        - XDEBUG_VER=${XDEBUG_VER}

  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
      args:
        - COMPOSER_VER=${COMPOSER_VER}
        - PHP_CLI_VER=${PHP_CLI_VER}
        - REDIS_VER=${REDIS_VER}
