version: "3"

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VER}
    depends_on:
      - elasticsearch
    volumes:
      - ./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - ${KIBANA_PORT}:5601
