version: "3"

services:

  pwa-studio:
    image: ${PWA_STUDIO_IMAGE}
    build:
      context: ${MAGE2PWA_PATH}
      args:
        - NODE_VER=${PWA_STUDIO_NODE_VER}
    env_file:
      - ./docker/pwa-studio/mage2pwa.env
    depends_on:
      - nginx
    volumes:
      - ${MAGE2PWA_PATH}/packages/peregrine/.storybook:/home/node/packages/peregrine/.storybook
      - ${MAGE2PWA_PATH}/packages/peregrine/scripts:/home/node/packages/peregrine/scripts
      - ${MAGE2PWA_PATH}/packages/peregrine/src:/home/node/packages/peregrine/src
      - ${MAGE2PWA_PATH}/packages/pwa-buildpack/src:/home/node/packages/pwa-buildpack/src
      - ${MAGE2PWA_PATH}/packages/upward-js/lib:/home/node/packages/upward-js/lib
      - ${MAGE2PWA_PATH}/packages/venia-concept/.storybook:/home/node/packages/venia-concept/.storybook
      - ${MAGE2PWA_PATH}/packages/venia-concept/src:/home/node/packages/venia-concept/src
      - ${MAGE2PWA_PATH}/packages/venia-concept/static:/home/node/packages/venia-concept/static
      - ./docker/pwa-studio/mage2pwa.env:/home/node/packages/venia-concept/.env
    ports:
      - 10000:10000

  cli:
    volumes:
      - ${MAGE2PWA_PATH}/packages/venia-concept/deployVeniaSampleData.sh:/var/www/html/deployVeniaSampleData.sh
